In [ ]:
1. What is a Python library? Why ^o we use Python libraries?

In [ ]:
A Python library is a collection of functions, methods, 
and modules that allows you to perform many actions without writing your code from scratch.
These libraries are developed to abstract away complex operations, provide reusable code for common tasks,
and facilitate programming by offering a wide range of functionalities. Libraries in Python can include anything 
from data manipulation and visualization tools to machine learning frameworks and network servers.

We use Python libraries for several reasons:

1. **Efficiency**:
    Using libraries, developers can save time and effort since they don't have to write and debug code for functionalities that a
    library already provides.

2. **Standardization**: Libraries often follow industry standards and best practices, ensuring that your code is up-to-date
and compatible with other systems and technologies.

3. **Complexity Management**: They help in managing complexity by encapsulating intricate code into simple-to-use functions. 
This makes it easier for developers to implement complex algorithms and processes.

4. **Community and Support**: Many Python libraries are open-source and have large communities behind them. 
This means you get access to a wealth of documentation, tutorials, and support forums, which can help solve problems and improve your code.

5. **Versatility**: Python libraries cover a broad range of application areas, 
from web development (like Django and Flask) to data analysis (like Pandas and NumPy), 
machine learning (like TensorFlow and scikit-learn), and beyond. This versatility makes 
Python a preferred choice for many developers across different domains.



In [ ]:
2. What is the ^ifference between Numpy array an^ List?

In [ ]:
Data Type:

NumPy Arrays:
Must contain elements of the same data type (int, float, string, bool, etc.). This promotes efficiency and compactness.
Supports advanced data types like complex numbers and arbitrary user-defined types.
Lists:
Can store elements of any data type, offering flexibility but sacrificing optimization.
Memory Usage:

NumPy Arrays:
Store elements contiguously in memory, significantly reducing overhead compared to lists.
Employ a single data type, further enhancing memory efficiency.
Lists:
Each element requires additional memory overhead for its data type and pointer information.
Storing heterogeneous types further increases memory usage.
Operations:

NumPy Arrays:
Optimized for mathematical and numerical operations using vectorized functions (e.g., numpy.add, numpy.sin).
Highly efficient for large datasets due to vectorized calculations and underlying C/C++ code.
Lists:
Python's built-in methods (e.g., +, -, *) handle operations element-wise, leading to slower performance for large datasets.
Applications:

NumPy Arrays:
Ideal for numerical computations, linear algebra, data analysis, machine learning, image processing, scientific computing, and more.
Excel at tasks involving large datasets and extensive calculations.
Lists:
Better suited for general-purpose data storage and manipulation where flexibility is paramount.
Useful for smaller datasets or when data types cannot be homogenized.
Choosing the Right Data Structure:

NumPy Arrays:
Use when you need:
Speed and efficiency for numerical operations.
Homogeneous data for large datasets.
Efficient memory usage.
Consider for large-scale numerical computing, machine learning, data analysis, and scientific simulations.
Lists:
Use when you need:
Flexibility to store different data types.
Simple data manipulation without extensive calculations.
Working with smaller datasets.
Consider for general-purpose data storage, manipulating mixed data types, or prototyping.

In [ ]:
3. Fin^ the shape, size an^ ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [15]:
import numpy as np
l = np.array([
    [1, 2, 3, 4],  # Note the added comma here
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])



In [16]:
l.size


12

In [12]:
l.shape

(3, 4)

In [13]:
l.ndim

2

In [ ]:
4. Write python co^e to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [14]:
import numpy as np

# Define the array using numpy
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Access the first row
first_row = array[0, :]

first_row


array([1, 2, 3, 4])

In [ ]:
5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [23]:
import numpy as np

# Define the array using numpy
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Access the element at the third row and fourth column
element = array[2, 3]

print(element)


12


In [ ]:
6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


In [24]:
import numpy as np

# Define the array using numpy
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Extract odd-indexed elements from the array
# This slices all rows, but steps through columns by 2, starting from the second column (index 1)
odd_indexed_elements = array[:, 1::2]

print(odd_indexed_elements)


[[ 2  4]
 [ 6  8]
 [10 12]]


In [ ]:
7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

In [26]:
import numpy as np
random_matrix = np.random.rand(3, 3)
random_matrix

array([[0.92637732, 0.11521598, 0.64601384],
       [0.91982955, 0.05071681, 0.49481569],
       [0.61641027, 0.24953065, 0.88119169]])

In [ ]:
8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?

In [27]:
# Generate a 2x3 matrix with uniform random values between 0 and 1
uniform_matrix = np.random.rand(2, 3)

# Generate a 2x3 matrix with standard normal random values
normal_matrix = np.random.randn(2, 3)

The main difference between np.random.rand and np.random.randn lies in the probability distribution they sample from:

np.random.rand:

Generates samples from a uniform distribution in the half-open interval [0, 1).
This means each value between 0 (inclusive) and 1 (exclusive) has an equal probability of being selected.
Useful when you need values spread evenly within a specific range.
np.random.randn:

Generates samples from the standard normal distribution, also known as the Gaussian distribution.
This distribution is bell-shaped, with most values concentrated around the mean (0) and fewer values further away.
Useful when you need values that naturally cluster around a central point with some variation.

In [28]:
uniform_matrix
normal_matrix

array([[ 1.36733867, -0.12997199,  1.2712781 ],
       [-1.26280238,  1.18185791,  0.51354802]])

In [ ]:
9. Write co^e to increase the ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [29]:
import numpy as np

# Define the array using numpy
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Increase the dimension of the array
# Adding a new axis at the end to convert from 2D to 3D
array_3d = array[:, :, np.newaxis]

print(array_3d.shape)


(3, 4, 1)


In [ ]:
10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [30]:
# Transpose the previously defined array in numpy
transposed_array = array.T

transposed_array


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
11. Consi^er the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
,+ I(dex wiLe multiplicatio'
]+ Matix multiplicatio'
+ Add both the maticK
-+ Subtact matix B om 
+ Diide Matix B by A

In [31]:
# Define matrices A2 and B2 using numpy
A2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

B2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Perform operations as requested
# Element-wise multiplication
elementwise_product = A2 * B2

# Matrix multiplication
matrix_product = np.dot(A2, B2.T)  # Transposing B2 for matching dimensions for dot product

# Add both the matrices
sum_matrices = A2 + B2

# Subtract matrix B from A
difference_matrices = A2 - B2

# Divide Matrix B by A (element-wise)
division_matrices = B2 / A2

# Display the results
elementwise_product, matrix_product, sum_matrices, difference_matrices, division_matrices


(array([[  1,   4,   9,  16],
        [ 25,  36,  49,  64],
        [ 81, 100, 121, 144]]),
 array([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]]),
 array([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]]),
 array([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

In [ ]:
12. Swapping the Byte Order of an Array in NumPy

In [ ]:
To swap the byte order of an array in NumPy, you can use the astype method with a specific dtype that specifies the desired byte order. 
For example, if you have an array of type int16 in little-endian byte order and you want to swap it to big-endian, you could use array.
astype('>i2'). Here, '>i2' specifies a big-endian integer of 2 bytes. Conversely, '<i2' would specify little-endian. 
The method does not have a single function call specifically named for swapping byte order, 
but using astype with byte order symbols ('>' for big-endian and '<' for little-endian) effectively achieves this.

In [ ]:
13. The Significance of np.linalg.inv

In [ ]:
The np.linalg.inv function in NumPy is used to compute the inverse of a given square matrix. The inverse of a matrix 
�
A is another matrix, often denoted as 
�
−
1
A 
−1
 , such that when 
�
A is multiplied by 
�
−
1
A 
−1
 , the result is the identity matrix.
    Computing the inverse of a matrix is significant in solving systems of linear equations, in linear algebra, 
    and in many fields of engineering and science. However, not all 
    matrices have inverses; a matrix must be square
    (same number of rows and columns) and non-singular (having a non-zero determinant) to have an inverse.

In [ ]:
14. What ^oes the np.reshape function ^o, an^ how is it use^?

In [32]:
import numpy as np

array = np.arange(6) # Creates an array [0, 1, 2, 3, 4, 5]
reshaped_array = array.reshape((3, 2)) # Reshapes the array to 3 rows and 2 columns


In [ ]:
15. What is broa^casting in Numpy?